[package]
name = "ahko3"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
    "ahko3-macros",
]

[dependencies]
ahko3-macros = {path = "ahko3-macros"}

[[example]]
name = "adder"
path = "examples/adder/src/lib.rs"
test = true
crate-type = ["lib"]
